version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151-jdk-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USER --password-stdin
      - run: ./publish.sh
