version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USER --password-stdin
      - run: ./publish.sh
